from ncp_aai.agents.codex_provider import (
    CitationInput,
    CodexOutputInput,
    ProviderMetadata,
    QuizItemInput,
)


def build_stub_codex_output(
    *,
    objective_id: str,
    topic_id: str | None,
    title: str,
    retrieved_chunks: list[dict],
) -> CodexOutputInput:
    if not retrieved_chunks:
        msg = "Local stub requires at least one retrieved chunk"
        raise ValueError(msg)

    first_chunk = retrieved_chunks[0]
    citation = CitationInput(
        source_chunk_id=first_chunk["chunk_id"],
        label="Retrieved local source",
        quote=first_chunk["text"][:220],
    )
    note_body = (
        f"# {title}\n\n"
        "This draft note is generated by the deterministic local stub. It summarizes the "
        "retrieved source chunk and exists to exercise Codex-shaped ingestion without invoking "
        "an external model.\n\n"
        f"Source excerpt: {first_chunk['text'][:500]}"
    )
    return CodexOutputInput(
        provider_metadata=ProviderMetadata(
            provider="local_stub", model="deterministic-hash", prompt_version="stub-v1"
        ),
        objective_id=objective_id,
        topic_id=topic_id,
        title=title,
        note_body=note_body,
        citations=[citation],
        quiz_items=[
            QuizItemInput(
                prompt=f"Which source-backed concept is most relevant to {title}?",
                options=[
                    "The cited local material",
                    "An uncited external claim",
                    "A missing provider key",
                    "A deleted source record",
                ],
                correct_option=0,
                rationale="The accepted answer is backed by the stored source chunk citation.",
                difficulty="easy",
                concept=title,
                citations=[citation],
            )
        ],
        gaps=["Replace this stub output with operator-reviewed Codex synthesis."],
    )
